---
apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: muc
  namespace: muc
spec:
  replicas: 1
---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: muc
  namespace: muc
spec:
  replicas: 1
  shards: 1
  keeperClusterRef:
    name: muc
---
apiVersion: v1
kind: Service
metadata:
  name: muc-clickhouse-nodeport
  namespace: muc
spec:
  type: NodePort
  selector:
    clickhouse.com/role: clickhouse-server
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      nodePort: 30802
    - name: tcp
      port: 9001
      targetPort: 9001
      nodePort: 30902
    - name: tcp-secure
      port: 9440
      targetPort: 9440
      nodePort: 30942
      protocol: TCP
